FROM node:20 AS builder

WORKDIR .

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM docker.io/library/nginx

COPY --from=builder /dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
