FROM node:20 AS builder

WORKDIR .

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: servir con un servidor estático
FROM docker.io/library/nginx:latest

COPY --from=builder ./dist /usr/share/nginx/html

# Opcional: sobreescribir configuración por defecto de NGINX si lo necesitas
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
