# API configuration
quarkus.http.root-path=/api

# Server configuration
quarkus.http.host=0.0.0.0

# DB Configuration
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=nico
%prod.quarkus.datasource.password=pass
%prod.quarkus.datasource.reactive.url=postgresql://db-service:5432/db_vibra

#%dev.quarkus.hibernate-orm.database.generation=update
%dev.quarkus.hibernate-orm.database.generation=drop-and-create

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.issuer=https://vibra.com
quarkus.smallrye-jwt.enabled=true

# DEBUG
#quarkus.log.category."org.hibernate".level=DEBUG
#quarkus.log.category."io.vertx".level=DEBUG

# CORS
%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=http://localhost:5173
%dev.quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS,PATCH
%dev.quarkus.http.cors.headers=origin, accept, authorization, content-type, x-requested-with
%dev.quarkus.http.cors.exposed-headers=location
%dev.quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.limits.max-body-size=50M
