# API configuration
quarkus.http.root-path=/api

# DB Configuration
quarkus.datasource.db-kind=postgresql
#quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.generation=drop-and-create

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.issuer=https://vibra.com
quarkus.smallrye-jwt.enabled=true

# DEBUG
#quarkus.log.category."org.hibernate".level=DEBUG
#quarkus.log.category."io.vertx".level=DEBUG

# CORS
quarkus.http.cors=true
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS, PATCH
quarkus.http.cors.headers=origin, accept, authorization, content-type, x-requested-with
quarkus.http.cors.exposed-headers=location
quarkus.http.cors.access-control-allow-credentials=true
