# DB Configuration
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=drop-and-create	

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.issuer=https://vibra.com
quarkus.smallrye-jwt.enabled=true